name = "AdaptiveEvaluation"
uuid = "fd8a4f78-b0f3-4fdc-976e-6632fb4fe704"
authors = ["Federico Cerisola <federico@cerisola.net>"]
version = "1.0.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
